---
title: "Error diagnostics: ENVE Multi-year analysis"
author: "Patricio R. Estevez Soto"
email: "patricio.estevez.14@ucl.ac.uk"
date: "20/10/2017"
output:
    md_document:
    variant: "markdown"
pandoc_args: "--smart"
---

# Set up, data input and pre-process

## Session info

We first check details of the session and system, and for reproducibility, we set the random seed.

```{r session, cache=FALSE}
starttime <- proc.time()
date()
sessionInfo()
set.seed(42)
options(scipen=0)
```

## Load packages and functions

Install custom package, requires `devtools`.

```{r install-victim}
# devtools::install_github("prestevez/victim")
```

Next we load the packages that we will use.

```{r packages}
# library(victim)
library(foreign)
# library(ggplot2)
# library(Cairo)
# library(knitr)
# library(texreg)
# library(lme4)
# library(glmmADMB)
# library(classInt)
# library(dplyr)
# library(reshape2)
# library(lmtest)
# library(car)
# library(pscl)
sessionInfo()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment="",
                      cache=TRUE,
                      dev=c("png", "CairoPDF"),
                      error=TRUE,
                      fig.width=5, fig.height=4)
options(knitr.kable.NA = '--')
```

# Other diagnostics

```
getwd()
list.files()
```

END
